<?php
/**
 * OrderRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InventoryClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InventoryAPI
 *
 * Orkiv Inventory API client
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace InventoryClient;

/**
 * OrderRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description OrderRequest
/**
 * @package     InventoryClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "OrderRequest"
     */
    public function testOrderRequest()
    {

    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {

    }

    /**
     * Test attribute "info_email"
     */
    public function testPropertyInfoEmail()
    {

    }

    /**
     * Test attribute "info_first"
     */
    public function testPropertyInfoFirst()
    {

    }

    /**
     * Test attribute "info_last"
     */
    public function testPropertyInfoLast()
    {

    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {

    }

    /**
     * Test attribute "shipset"
     */
    public function testPropertyShipset()
    {

    }

    /**
     * Test attribute "info_adr1"
     */
    public function testPropertyInfoAdr1()
    {

    }

    /**
     * Test attribute "info_adr2"
     */
    public function testPropertyInfoAdr2()
    {

    }

    /**
     * Test attribute "info_cty"
     */
    public function testPropertyInfoCty()
    {

    }

    /**
     * Test attribute "info_zip"
     */
    public function testPropertyInfoZip()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "info_sadr1"
     */
    public function testPropertyInfoSadr1()
    {

    }

    /**
     * Test attribute "info_sadr2"
     */
    public function testPropertyInfoSadr2()
    {

    }

    /**
     * Test attribute "info_scty"
     */
    public function testPropertyInfoScty()
    {

    }

    /**
     * Test attribute "info_szip"
     */
    public function testPropertyInfoSzip()
    {

    }

    /**
     * Test attribute "sstate"
     */
    public function testPropertySstate()
    {

    }

    /**
     * Test attribute "tax_amount"
     */
    public function testPropertyTaxAmount()
    {

    }

    /**
     * Test attribute "shipping_amount"
     */
    public function testPropertyShippingAmount()
    {

    }

    /**
     * Test attribute "amount_total"
     */
    public function testPropertyAmountTotal()
    {

    }

}
