<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  InventoryClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InventoryAPI
 *
 * Orkiv Inventory API client
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace InventoryClient;

use \InventoryClient\Configuration;
use \InventoryClient\ApiClient;
use \InventoryClient\ApiException;
use \InventoryClient\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  InventoryClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for allGet
     *
     * .
     *
     */
    public function testAllGet()
    {

    }

    /**
     * Test case for categoriesDelete
     *
     * .
     *
     */
    public function testCategoriesDelete()
    {

    }

    /**
     * Test case for categoriesPost
     *
     * .
     *
     */
    public function testCategoriesPost()
    {

    }

    /**
     * Test case for categoriesPut
     *
     * .
     *
     */
    public function testCategoriesPut()
    {

    }

    /**
     * Test case for itemAddPost
     *
     * .
     *
     */
    public function testItemAddPost()
    {

    }

    /**
     * Test case for itemAddbulkPost
     *
     * .
     *
     */
    public function testItemAddbulkPost()
    {

    }

    /**
     * Test case for itemDelete
     *
     * .
     *
     */
    public function testItemDelete()
    {

    }

    /**
     * Test case for itemGet
     *
     * .
     *
     */
    public function testItemGet()
    {

    }

    /**
     * Test case for itemMediaDelete
     *
     * .
     *
     */
    public function testItemMediaDelete()
    {

    }

    /**
     * Test case for itemMediaPost
     *
     * .
     *
     */
    public function testItemMediaPost()
    {

    }

    /**
     * Test case for itemPut
     *
     * .
     *
     */
    public function testItemPut()
    {

    }

    /**
     * Test case for itemsCountPost
     *
     * .
     *
     */
    public function testItemsCountPost()
    {

    }

    /**
     * Test case for itemsPost
     *
     * .
     *
     */
    public function testItemsPost()
    {

    }

    /**
     * Test case for ordersPost
     *
     * .
     *
     */
    public function testOrdersPost()
    {

    }

    /**
     * Test case for ordersServicesPost
     *
     * .
     *
     */
    public function testOrdersServicesPost()
    {

    }

    /**
     * Test case for queryPost
     *
     * .
     *
     */
    public function testQueryPost()
    {

    }

    /**
     * Test case for servicesDelete
     *
     * .
     *
     */
    public function testServicesDelete()
    {

    }

    /**
     * Test case for servicesGet
     *
     * .
     *
     */
    public function testServicesGet()
    {

    }

    /**
     * Test case for servicesOpenGet
     *
     * .
     *
     */
    public function testServicesOpenGet()
    {

    }

    /**
     * Test case for servicesPost
     *
     * .
     *
     */
    public function testServicesPost()
    {

    }

    /**
     * Test case for servicesPut
     *
     * .
     *
     */
    public function testServicesPut()
    {

    }

    /**
     * Test case for variationDelete
     *
     * .
     *
     */
    public function testVariationDelete()
    {

    }

    /**
     * Test case for variationGet
     *
     * .
     *
     */
    public function testVariationGet()
    {

    }

    /**
     * Test case for variationPost
     *
     * .
     *
     */
    public function testVariationPost()
    {

    }

    /**
     * Test case for variationPut
     *
     * .
     *
     */
    public function testVariationPut()
    {

    }

    /**
     * Test case for writeDelete
     *
     * .
     *
     */
    public function testWriteDelete()
    {

    }

    /**
     * Test case for writePost
     *
     * .
     *
     */
    public function testWritePost()
    {

    }

}
